const roseResults = {
  data: [
    {
      id: 175704,
      common_name: "Field rose",
      slug: "rosa-arvensis",
      scientific_name: "Rosa arvensis",
      year: 1762,
      bibliography: "Fl. Angl.: 192 (1762)",
      author: "Huds.",
      status: "accepted",
      rank: "species",
      family_common_name: "Rose family",
      genus_id: 5912,
      image_url:
        "https://bs.floristic.org/image/o/afc9f4d7ce137f04746413f629330948b73e79d3",
      synonyms: [
        "Rosa stylaris",
        "Rosa lucronensis",
        "Rosa systyla",
        "Rosa canina var. evanida",
        "Rosa modesta",
        "Rosa brevistyla",
        "Rosa maluqueri",
        "Rosa leucochroa",
        "Rosa immitis",
        "Rosa nevadensis",
        "Rosa rustica",
        "Rosa reptans",
        "Rosa stylosa",
        "Rosa erronea",
        "Rosa halleri",
        "Rosa phalacropoda",
        "Rosa sylvestris",
        "Rosa serpens",
        "Rosa herporhodon",
        "Rosa baldensis",
        "Rosa ovata",
        "Rosa macrostylis",
        "Rosa fastigiata",
        "Rosa commiserata",
        "Rosa scandens",
      ],
      genus: "Rosa",
      family: "Rosaceae",
      links: {
        self: "/api/v1/species/rosa-arvensis",
        plant: "/api/v1/plants/rosa-arvensis",
        genus: "/api/v1/genus/rosa",
      },
    },
    {
      id: 175724,
      common_name: "Dog rose",
      slug: "rosa-canina",
      scientific_name: "Rosa canina",
      year: 1753,
      bibliography: "Sp. pl. 1:491.  1753",
      author: "L.",
      status: "accepted",
      rank: "species",
      family_common_name: "Rose family",
      genus_id: 5912,
      image_url:
        "https://bs.floristic.org/image/o/658bff43fbf3b22296b0206094ab2d01852c41e5",
      synonyms: [
        "Rosa transsilvanica",
        "Rosa simplicidens",
        "Rosa opaca",
        "Rosa mandonii",
        "Rosa maeotica",
        "Rosa lonaczevskii",
        "Rosa didoensis",
        "Rosa biebersteiniana",
        "Rosa achburensis",
        "Rosa oreades",
        "Rosa kalmiussica",
        "Rosa rubescens",
        "Rosa pratincola",
        "Rosa willibaldii",
        "Rosa sphaeroidea",
        "Rosa macroacantha",
        "Rosa lutetiana",
        "Rosa senticosa",
        "Rosa canina var. ramosissima",
        "Rosa glaberrima",
        "Rosa litigiosa",
        "Rosa heterostyla",
        "Rosa stipularis",
        "Rosa rougeonensis",
        "Rosa afzeliana",
        "Rosa × trichoneura",
        "Rosa × ancarensis",
        "Rosa pubens",
        "Rosa edita",
        "Rosa hirtella",
        "Rosa belgradensis",
        "Rosa caucasica",
        "Rosa montivaga",
        "Rosa amansii",
        "Rosa mediata",
        "Rosa curticola",
        "Rosa prutensis",
        "Rosa marisensis",
        "Rosa dumosa",
        "Rosa adenocalyx",
        "Rosa frondosa",
        "Rosa nemophila",
        "Rosa frivaldskyi",
        "Rosa swartziana",
        "Rosa canina var. glandulosa",
        "Rosa vinealis",
        "Rosa canina var. vulgaris",
        "Rosa cladoleia",
        "Rosa sphaerica",
        "Rosa fissispina",
        "Rosa sarmentacea",
        "Rosa touranginiana",
        "Rosa burnatii",
        "Rosa inconspicua",
        "Rosa maialis",
        "Rosa erythrantha",
        "Rosa acanthina",
        "Rosa separabilis",
        "Rosa psilophylla",
        "Rosa sylvularum",
        "Rosa polyodon",
        "Rosa cinerosa",
        "Rosa flexibilis",
        "Rosa dilucida",
        "Rosa spuria",
        "Rosa flavidifolia",
        "Rosa oblongata",
        "Rosa mollardiana",
      ],
      genus: "Rosa",
      family: "Rosaceae",
      links: {
        self: "/api/v1/species/rosa-canina",
        plant: "/api/v1/plants/rosa-canina",
        genus: "/api/v1/genus/rosa",
      },
    },
    {
      id: 175834,
      common_name: "Rugosa rose",
      slug: "rosa-rugosa",
      scientific_name: "Rosa rugosa",
      year: 1784,
      bibliography: "J.A.Murray, Syst. Veg., ed. 14: 473 (1784)",
      author: "Thunb.",
      status: "accepted",
      rank: "species",
      family_common_name: "Rose family",
      genus_id: 5912,
      image_url:
        "https://bs.floristic.org/image/o/fe957b1a87df808443782ad72c2c0ddec0729370",
      synonyms: [
        "Rosa ferox",
        "Rosa coruscans",
        "Rosa rugosa var. albiflora",
        "Rosa andreae",
        "Rosa kamtchatica",
        "Rosa regeliana",
      ],
      genus: "Rosa",
      family: "Rosaceae",
      links: {
        self: "/api/v1/species/rosa-rugosa",
        plant: "/api/v1/plants/rosa-rugosa",
        genus: "/api/v1/genus/rosa",
      },
    },
    {
      id: 175851,
      common_name: "Scotch rose",
      slug: "rosa-spinosissima",
      scientific_name: "Rosa spinosissima",
      year: 1753,
      bibliography: "Sp. pl. 1:491.  1753",
      author: "L.",
      status: "accepted",
      rank: "species",
      family_common_name: "Rose family",
      genus_id: 5912,
      image_url:
        "https://bs.floristic.org/image/o/673b94a9fbe96fe101913d897dae08930e082ea8",
      synonyms: [
        "Rosa hracziana",
        "Rosa gracilipes",
        "Rosa elasmacantha",
        "Rosa poteriifolia",
        "Rosa pimpinellifolia subsp. myriacantha",
        "Rosa borealis",
        "Rosa ripartii",
        "Rosa gentilis",
        "Rosa pulchella",
        "Rosa besseri",
        "Rosa rupincola",
        "Rosa mathonnetii",
        "Rosa granatensis",
        "Rosa agustiana",
        "Rosa melanocarpa",
        "Rosa javalambrensis",
        "Rosa consimilis",
        "Rosa myriacantha",
        "Rosa chamaerhodon",
        "Rosa spreta",
        "Rosa scotica",
        "Rosa humensis",
        "Rosa macropoda",
        "Rosa lutescens",
        "Rosa rubella",
        "Rosa mitissima",
        "Rosa tschatyrdagi",
        "Rosa sibirica",
        "Rosa pimpinellifolia",
      ],
      genus: "Rosa",
      family: "Rosaceae",
      links: {
        self: "/api/v1/species/rosa-spinosissima",
        plant: "/api/v1/plants/rosa-spinosissima",
        genus: "/api/v1/genus/rosa",
      },
    },
    {
      id: 175818,
      common_name: "Alpine rose",
      slug: "rosa-pendulina",
      scientific_name: "Rosa pendulina",
      year: 1753,
      bibliography: "Sp. Pl.: 492 (1753)",
      author: "L.",
      status: "accepted",
      rank: "species",
      family_common_name: "Rose family",
      genus_id: 5912,
      image_url:
        "https://bs.floristic.org/image/o/3894b3cacd2c46acd31ecf93187983b36ad080fa",
      synonyms: [
        "Rosa tenuiflora",
        "Rosa majalis var. globosa",
        "Rosa diplacantha",
        "Rosa rupestris",
        "Rosa pendula",
        "Rosa semisimplex",
        "Rosa alpina",
        "Rosa inermis",
        "Rosa adjecta",
        "Rosa pyrenaica",
        "Rosa balcanica",
        "Rosa villarsii",
        "Rosa affinis",
        "Rosa adenophora",
        "Rosa coccialba",
        "Rosa alpiniformis",
        "Rosa hybrida",
        "Rosa lagenaria",
        "Rosa malyi",
        "Rosa stenodonta",
        "Rosa odoratissima",
        "Rosa cinnamomea",
      ],
      genus: "Rosa",
      family: "Rosaceae",
      links: {
        self: "/api/v1/species/rosa-pendulina",
        plant: "/api/v1/plants/rosa-pendulina",
        genus: "/api/v1/genus/rosa",
      },
    },
    {
      id: 175790,
      common_name: "Multiflora rose",
      slug: "rosa-multiflora",
      scientific_name: "Rosa multiflora",
      year: 1784,
      bibliography: "J.A.Murray, Syst. Veg. ed. 14: 474 (1784)",
      author: "Thunb.",
      status: "accepted",
      rank: "species",
      family_common_name: "Rose family",
      genus_id: 5912,
      image_url:
        "https://bs.floristic.org/image/o/640d0c14fec8abdf25abd81a9124f83ad44404d2",
      synonyms: [
        "Rosa multiflora var. alboplena",
        "Rosa polyantha",
        "Rosa quelpaertensis",
        "Rosa multiflora f. inermis",
        "Rosa thyrsiflora",
        "Rosa polyantha f. roseipetala",
        "Rosa thunbergii",
        "Rosa watsoniana",
      ],
      genus: "Rosa",
      family: "Rosaceae",
      links: {
        self: "/api/v1/species/rosa-multiflora",
        plant: "/api/v1/plants/rosa-multiflora",
        genus: "/api/v1/genus/rosa",
      },
    },
    {
      id: 175832,
      common_name: "Sweetbriar rose",
      slug: "rosa-rubiginosa",
      scientific_name: "Rosa rubiginosa",
      year: 1771,
      bibliography: "Mant. Pl. 2: 564 (1771)",
      author: "L.",
      status: "accepted",
      rank: "species",
      family_common_name: "Rose family",
      genus_id: 5912,
      image_url:
        "https://bs.floristic.org/image/o/1001f7c5af8e1809a519a1c95dac41b948c55a0a",
      synonyms: [
        "Rosa rubiginosa subsp. columnifera",
        "Rosa gremlii",
        "Rosa × almeriensis",
        "Rosa eglanteria var. glabra",
        "Rosa walpoleana",
        "Rosa × braunii",
        "Rosa umbellata",
        "Rosa moutinii",
        "Rosa resinosa",
        "Rosa eglanteria",
      ],
      genus: "Rosa",
      family: "Rosaceae",
      links: {
        self: "/api/v1/species/rosa-rubiginosa",
        plant: "/api/v1/plants/rosa-rubiginosa",
        genus: "/api/v1/genus/rosa",
      },
    },
    {
      id: 175725,
      common_name: "Corymb rose",
      slug: "rosa-corymbifera",
      scientific_name: "Rosa corymbifera",
      year: 1790,
      bibliography: "Vers. forstbot. Beschr. 319.  1790",
      author: "Borkh.",
      status: "accepted",
      rank: "species",
      family_common_name: "Rose family",
      genus_id: 5912,
      image_url:
        "https://bs.floristic.org/image/o/1a653d14999a80c2a396275c8c3024c1936025b5",
      synonyms: [
        "Rosa tesquicola",
        "Rosa lapidosa",
        "Rosa canina var. dumetorum",
        "Rosa dumetorum",
        "Rosa obtusifolia",
        "Rosa platyphylla",
        "Rosa uncinella",
      ],
      genus: "Rosa",
      family: "Rosaceae",
      links: {
        self: "/api/v1/species/rosa-corymbifera",
        plant: "/api/v1/plants/rosa-corymbifera",
        genus: "/api/v1/genus/rosa",
      },
    },
    {
      id: 175868,
      common_name: "Whitewoolly rose",
      slug: "rosa-tomentosa",
      scientific_name: "Rosa tomentosa",
      year: 1800,
      bibliography: "Fl. Brit. 2: 539 (1800)",
      author: "Sm.",
      status: "accepted",
      rank: "species",
      family_common_name: "Rose family",
      genus_id: 5912,
      image_url:
        "https://bs.floristic.org/image/o/d95516e7ddc7ce8c33b7aadc135effdd28be9fd9",
      synonyms: [
        "Rosa cinerascens",
        "Rosa tomentosa var. globulosa",
        "Rosa cuspidata",
        "Rosa subglobosa",
        "Rosa pseudocuspidata",
        "Rosa borysthenica",
        "Rosa mollissima",
      ],
      genus: "Rosa",
      family: "Rosaceae",
      links: {
        self: "/api/v1/species/rosa-tomentosa",
        plant: "/api/v1/plants/rosa-tomentosa",
        genus: "/api/v1/genus/rosa",
      },
    },
    {
      id: 175783,
      common_name: "Soft downy rose",
      slug: "rosa-mollis",
      scientific_name: "Rosa mollis",
      year: 1813,
      bibliography: "Engl. bot. 35: t. 2459.  1813",
      author: "Sm.",
      status: "accepted",
      rank: "species",
      family_common_name: "Rose family",
      genus_id: 5912,
      image_url:
        "https://bs.floristic.org/image/o/cde6f72351c1b0f0441fbdc1313765be3650f95d",
      synonyms: [
        "Rosa zakatalensis",
        "Rosa villosa subsp. mollis",
        "Rosa cujavica",
        "Rosa heldreichii",
        "Rosa pseudorubiginosa",
        "Rosa kitaibelii",
      ],
      genus: "Rosa",
      family: "Rosaceae",
      links: {
        self: "/api/v1/species/rosa-mollis",
        plant: "/api/v1/plants/rosa-mollis",
        genus: "/api/v1/genus/rosa",
      },
    },
    {
      id: 175682,
      common_name: "Prickly rose",
      slug: "rosa-acicularis",
      scientific_name: "Rosa acicularis",
      year: 1820,
      bibliography: "Ros. Monogr.: 44 (1820)",
      author: "Lindl.",
      status: "accepted",
      rank: "species",
      family_common_name: "Rose family",
      genus_id: 5912,
      image_url: null,
      synonyms: [
        "Rosa granulosa",
        "Rosa gmelinii",
        "Rosa acicularis var. glandulifolia",
        "Rosa fauriei",
        "Rosa carelica",
        "Rosa taquetii",
        "Rosa korsakoviensis",
      ],
      genus: "Rosa",
      family: "Rosaceae",
      links: {
        self: "/api/v1/species/rosa-acicularis",
        plant: "/api/v1/plants/rosa-acicularis",
        genus: "/api/v1/genus/rosa",
      },
    },
    {
      id: 175754,
      common_name: "Glaucous rose",
      slug: "rosa-glauca",
      scientific_name: "Rosa glauca",
      year: 1788,
      bibliography: "Hist. & Mém. Acad. Roy. Sci. Toulouse 3: 326 (1788)",
      author: "Pourr.",
      status: "accepted",
      rank: "species",
      family_common_name: "Rose family",
      genus_id: 5912,
      image_url:
        "https://bs.floristic.org/image/o/da6e02749b22be275583eb4eeaa3d3ffe47fc26c",
      synonyms: [
        "Rosa glaucescens",
        "Rosa ferruginea",
        "Rosa rubicunda",
        "Rosa lurida",
        "Rosa ilseana",
        "Rosa livida",
      ],
      genus: "Rosa",
      family: "Rosaceae",
      links: {
        self: "/api/v1/species/rosa-glauca",
        plant: "/api/v1/plants/rosa-glauca",
        genus: "/api/v1/genus/rosa",
      },
    },
    {
      id: 175760,
      common_name: "French rose",
      slug: "rosa-gallica",
      scientific_name: "Rosa gallica",
      year: 1753,
      bibliography: "Sp. pl. 1:492.  1753",
      author: "L.",
      status: "accepted",
      rank: "species",
      family_common_name: "Rose family",
      genus_id: 5912,
      image_url:
        "https://bs.floristic.org/image/o/76cffed0aa332c6e323ff15ea15a93a23c1f671a",
      synonyms: [
        "Rosa chrshanovskii",
        "Rosa grossheimii",
        "Rosa homoacantha",
        "Rosa livescens",
        "Rosa parviuscula",
        "Rosa talijevii",
        "Rosa ucrainica",
        "Rosa subpygmaea",
        "Rosa scabrata",
        "Rosa schistosa",
        "Rosa ratomskiana",
        "Rosa krynkensis",
        "Rosa crenatula",
        "Rosa grandiflora",
        "Rosa austriaca var. officinalis",
        "Rosa pygmaea",
        "Rosa repens",
        "Rosa pumila var. tricolor",
        "Rosa czackiana",
        "Rosa crenulata",
        "Rosa gallica var. versicolor",
        "Rosa gallica var. gallica",
        "Rosa sylvatica",
        "Rosa assimilis",
        "Rosa virescens",
        "Rosa minimalis",
        "Rosa olympica",
        "Rosa velutinaeflora",
        "Rosa pumila var. rosamundi",
        "Rosa ruralis",
        "Rosa rubra",
        "Rosa cordifolia",
        "Rosa cordata",
        "Rosa provincialis",
        "Rosa pumila var. holosericea",
        "Rosa pumila",
        "Rosa pumila var. subnigra",
        "Rosa heteracantha",
        "Rosa pinnatifida",
        "Rosa arvina",
        "Rosa belgica",
        "Rosa atropurpurea",
        "Rosa racemosa",
        "Rosa austriaca",
        "Rosa hispida",
        "Rosa holosericea",
        "Rosa tenuis",
        "Rosa oligacantha",
        "Rosa mirogojana",
        "Rosa gallica var. officinalis",
      ],
      genus: "Rosa",
      family: "Rosaceae",
      links: {
        self: "/api/v1/species/rosa-gallica",
        plant: "/api/v1/plants/rosa-gallica",
        genus: "/api/v1/genus/rosa",
      },
    },
    {
      id: 1059394,
      common_name: "Apple rose",
      slug: "rosa-x-involuta",
      scientific_name: "Rosa × involuta",
      year: 1804,
      bibliography: "Fl. Brit. 3: 1398 (1804)",
      author: "Sm.",
      status: "accepted",
      rank: "hybrid",
      family_common_name: "Rose family",
      genus_id: 5912,
      image_url:
        "https://bs.floristic.org/image/o/2231e90fbfc896ecdfeed0d022a9b3f5a61ad666",
      synonyms: [
        "Rosa borissovae",
        "Rosa coziae",
        "Rosa × doniana",
        "Rosa × gracilis",
        "Rosa villosa",
      ],
      genus: "Rosa",
      family: "Rosaceae",
      links: {
        self: "/api/v1/species/rosa-x-involuta",
        plant: "/api/v1/plants/rosa-x-involuta",
        genus: "/api/v1/genus/rosa",
      },
    },
    {
      id: 175726,
      common_name: "Carolina rose",
      slug: "rosa-carolina",
      scientific_name: "Rosa carolina",
      year: 1753,
      bibliography: "Sp. Pl.: 492 (1753)",
      author: "L.",
      status: "accepted",
      rank: "species",
      family_common_name: "Rose family",
      genus_id: 5912,
      image_url:
        "http://d2seqvvyy3b8p2.cloudfront.net/beb61efe68cc0854b20f073222cf5198.jpg",
      synonyms: [
        "Rosa pratensis",
        "Rosa carolina var. carolina",
        "Rosa humilis",
        "Rosa pusilla",
        "Rosa humilis var. villosa",
        "Rosa virginiana subsp. humilis",
        "Rosa carolina var. setigera",
        "Rosa serrulata",
        "Rosa lyonii",
        "Rosa carolina var. villosa",
        "Rosa carolina var. lyonii",
        "Rosa carolina var. grandiflora",
      ],
      genus: "Rosa",
      family: "Rosaceae",
      links: {
        self: "/api/v1/species/rosa-carolina",
        plant: "/api/v1/plants/rosa-carolina",
        genus: "/api/v1/genus/rosa",
      },
    },
    {
      id: 175846,
      common_name: "Sherard's downy rose",
      slug: "rosa-sherardii",
      scientific_name: "Rosa sherardii",
      year: 1813,
      bibliography: "Welsh Botanol. 1: 49 (1813)",
      author: "Davies",
      status: "accepted",
      rank: "species",
      family_common_name: "Rose family",
      genus_id: 5912,
      image_url:
        "https://bs.floristic.org/image/o/a56c098ebdb981794c0b9744ee8c4fae86a74d96",
      synonyms: ["Rosa omissa"],
      genus: "Rosa",
      family: "Rosaceae",
      links: {
        self: "/api/v1/species/rosa-sherardii",
        plant: "/api/v1/plants/rosa-sherardii",
        genus: "/api/v1/genus/rosa",
      },
    },
    {
      id: 175882,
      common_name: "Woods' rose",
      slug: "rosa-woodsii",
      scientific_name: "Rosa woodsii",
      year: 1820,
      bibliography: "Ros. Monogr.: 21 (1820)",
      author: "Lindl.",
      status: "accepted",
      rank: "species",
      family_common_name: "Rose family",
      genus_id: 5912,
      image_url:
        "https://bs.floristic.org/image/o/67e4841aa39032d0377161a5059470e09769ba25",
      synonyms: [
        "Rosa woodsii var. fendleri",
        "Rosa terrens",
        "Rosa standleyi",
        "Rosa macounii",
        "Rosa hypoleuca",
        "Rosa fendleri",
      ],
      genus: "Rosa",
      family: "Rosaceae",
      links: {
        self: "/api/v1/species/rosa-woodsii",
        plant: "/api/v1/plants/rosa-woodsii",
        genus: "/api/v1/genus/rosa",
      },
    },
    {
      id: 175745,
      common_name: "Chinese rose",
      slug: "rosa-chinensis",
      scientific_name: "Rosa chinensis",
      year: 1768,
      bibliography: "Observ. Bot. 3: 7 (1768)",
      author: "Jacq.",
      status: "accepted",
      rank: "species",
      family_common_name: "Rose family",
      genus_id: 5912,
      image_url:
        "https://bs.floristic.org/image/o/5ffdd7134abcd7e2e386dc1ba1d09774e2264b1e",
      synonyms: [
        "Rosa sinica",
        "Rosa bengalensis chinensis",
        "Rosa nankinensis",
        "Rosa semperflorens",
        "Rosa longifolia",
        "Rosa diversifolia",
      ],
      genus: "Rosa",
      family: "Rosaceae",
      links: {
        self: "/api/v1/species/rosa-chinensis",
        plant: "/api/v1/plants/rosa-chinensis",
        genus: "/api/v1/genus/rosa",
      },
    },
    {
      id: 175775,
      common_name: "Double cinnamon rose",
      slug: "rosa-majalis",
      scientific_name: "Rosa majalis",
      year: 1762,
      bibliography: "De Rosa: 8 (1762)",
      author: "Herrm.",
      status: "accepted",
      rank: "species",
      family_common_name: "Rose family",
      genus_id: 5912,
      image_url:
        "https://bs.floristic.org/image/o/e1d2d579e39f48cd76b7e5107844b2081b3ab45d",
      synonyms: [
        "Rosa fischeriana",
        "Rosa foecundissima",
        "Rosa fraxinifolia",
        "Rosa collincola",
        "Rosa majalis var. petropolitana",
      ],
      genus: "Rosa",
      family: "Rosaceae",
      links: {
        self: "/api/v1/species/rosa-majalis",
        plant: "/api/v1/plants/rosa-majalis",
        genus: "/api/v1/genus/rosa",
      },
    },
    {
      id: 1059191,
      common_name: "Elliptical rose",
      slug: "rosa-inodora",
      scientific_name: "Rosa inodora",
      year: 1814,
      bibliography: "Novit. Fl. Svec. 1: 9 (1814)",
      author: "Fr.",
      status: "accepted",
      rank: "species",
      family_common_name: "Rose family",
      genus_id: 5912,
      image_url:
        "https://bs.floristic.org/image/o/a6264ab822e0adf7cb1e89534df67fd0c439bbd1",
      synonyms: [
        "Rosa szaboi",
        "Rosa inodora var. szaboi",
        "Rosa graveolens",
        "Rosa elliptica",
      ],
      genus: "Rosa",
      family: "Rosaceae",
      links: {
        self: "/api/v1/species/rosa-inodora",
        plant: "/api/v1/plants/rosa-inodora",
        genus: "/api/v1/genus/rosa",
      },
    },
  ],
  links: {
    self: "/api/v1/plants/search?q=rose",
    first: "/api/v1/plants/search?page=1&q=rose",
    next: "/api/v1/plants/search?page=2&q=rose",
    last: "/api/v1/plants/search?page=430&q=rose",
  },
  meta: {
    total: 8583,
  },
};

module.exports = {
  roseResults,
};
